name: mapbox_geocoding
description: Mapbox Geocoding API library in order to make forward and reverse geocoding.
version: 0.0.6
homepage: https://github.com/berkayoruc/mapbox_geocoding/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
