name: mapbox_geocoding
description: Mapbox Geocoding API library in order to make forward and reverse geocoding.
version: 0.0.10
author: 'Berkay Oruç <berkayoruc0@gmail.com>'
homepage: https://github.com/berkayoruc/mapbox_geocoding/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
